const LABELS={dongbei:[["direct","直接可用","跨地域秒懂，放进严肃技术解释也自然"],["marked","能懂但有地域标记","意思清楚，但应低频或看语境"],["local","不确定 / 偏地方","可能让普通话读者停下来解码"],["exclude","排除","表演、冒犯、含混或没有解释价值"]],terms:[["tier1","Tier 1 · 无需解释","跨领域技术读者可默认认识"],["tier2","Tier 2 · 首次简释","保留英文，第一次需要一句说明"],["specialist","更专业 · 按需展开","只在当前论证需要时解释机制"],["uncertain","不确定","需要更多受众标注或依上下文决定"]]};
let deck="dongbei",index=0,unlabeledOnly=false;const key=d=>`dongbei-explainer-annotations-${annotationData.version}-${d}`;const read=d=>JSON.parse(localStorage.getItem(key(d))||"{}");const write=(d,v)=>localStorage.setItem(key(d),JSON.stringify(v));const $=id=>document.getElementById(id);
function visibleItems(){const all=annotationData[deck];if(!unlabeledOnly)return all;const a=read(deck);return all.filter(x=>!a[x.id]?.label)}
function render(){const list=visibleItems();if(index>=list.length)index=Math.max(0,list.length-1);const item=list[index],answers=read(deck),done=Object.values(answers).filter(x=>x.label).length;$("deck-name").textContent=deck==="dongbei"?"东北表达":"英文术语";$("progress-text").textContent=`${done} / ${annotationData[deck].length}`;$("progress-bar").style.width=`${100*done/annotationData[deck].length}%`;if(!item){$("candidate").textContent="这组都标完了";$("context").textContent="可以导出 JSON，或切回全部复查。";$("choices").innerHTML="";$("position").textContent="";return}$("category").textContent=item.category.replace(/^term-/,"");$("position").textContent=`${index+1} / ${list.length}`;$("candidate").textContent=item.term;$("context").textContent=item.context;$("question").textContent=deck==="dongbei"?"你会怎么定它的可懂性边界？":"你会把它放在哪个熟悉度层？";$("note").value=answers[item.id]?.note||"";$("choices").innerHTML=LABELS[deck].map(([v,l,h])=>`<button class="choice ${answers[item.id]?.label===v?"selected":""}" data-value="${v}"><strong>${l}</strong><br><small>${h}</small></button>`).join("");document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>answer(item,b.dataset.value));$("legend").innerHTML=`<strong>当前判断口径：</strong> ${LABELS[deck].map(x=>`${x[1]}：${x[2]}`).join("；")}`}
function answer(item,label){const a=read(deck);a[item.id]={label,note:$("note").value.trim(),updated_at:new Date().toISOString()};write(deck,a);render()}
function persistNote(){const item=visibleItems()[index];if(!item)return;const a=read(deck);if(!a[item.id])return;a[item.id].note=$("note").value.trim();write(deck,a)}
function move(delta){persistNote();const n=visibleItems().length;index=Math.min(Math.max(index+delta,0),Math.max(n-1,0));render()}
document.querySelectorAll(".tab").forEach(tab=>tab.onclick=()=>{persistNote();deck=tab.dataset.deck;index=0;document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===tab));render()});
$("prev").onclick=()=>move(-1);$("next").onclick=()=>move(1);$("skip").onclick=()=>move(1);$("show-unlabeled").onclick=()=>{unlabeledOnly=!unlabeledOnly;index=0;$("show-unlabeled").textContent=unlabeledOnly?"显示全部":"只看未标";render()};
$("reset").onclick=()=>{if(confirm("清空当前组的全部本地标注？此操作不能撤销。")){localStorage.removeItem(key(deck));index=0;render()}};
$("export").onclick=()=>{persistNote();const payload={schema_version:1,dataset_version:annotationData.version,exported_at:new Date().toISOString(),dongbei:read("dongbei"),terms:read("terms")};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`dongbei-explainer-annotations-${Date.now()}.json`;link.click();URL.revokeObjectURL(link.href)};
document.addEventListener("keydown",event=>{if(event.target.tagName==="TEXTAREA")return;if(event.key==="ArrowLeft")move(-1);if(event.key==="ArrowRight")move(1);const i=Number(event.key)-1;if(i>=0&&i<4){const item=visibleItems()[index];if(item)answer(item,LABELS[deck][i][0])}});render();
