/* Broad, unvalidated candidate pools. Human labels define policy. */
const DB_VERSION="2026-08-28.1";
function items(raw,category,template){return raw.split("|").map((term,i)=>({id:`${category}-${i+1}`,term,category,context:template.replace("{}",term)}))}
const dongbeiCandidates=[
...items("啥|咋|咋办|咋回事|咋整|为啥|干啥|弄啥|这玩意儿|那玩意儿|整|整明白|没整明白|怎么整|别整这个|搁这儿|搁哪儿|卡在这儿|真正卡住的是|说白了|说到底|归根结底|其实就这么回事|你先这么理解|先别管这个名字|先看它干了啥|原来是…现在是…|它改的就是这一步|问题出在这儿|这一步没跑|这俩不是一回事|别混一块儿|不能硬比|先捋一遍|咱从头捋|往下走一步|回头再看|到这一步|这就对上了|这么一来|反过来看|你看啊|注意这块儿|关键在这儿|麻烦在这儿|坑在这儿|绕不过去|跑偏了|对不上|接不上|挂住了|堵住了|攒着|摊开看|掰开看|拆开看|顺着走|挨个看|一股脑|稀里糊涂|磨磨唧唧|费劲|折腾|白忙活|压根儿|根本不是|可不是说|不是…而是…|别急着下结论|先把这层拿掉|中间多了一层|前面省了|后面还得做|该算的还得算|没凭空消失|账还在|老账|新来的这一份|各干各的|谁来都行|谁满足谁来|写死了|松绑|兜底|顶上去|拎出来|塞进去|掏出来|留着别重算|从头来一遍|硬塞|硬比|绕一圈|多走一步|少走一步|一步到位|一回事儿|有啥区别|到底图啥|到底发生了啥|到底改了啥|到底省了啥|到底没解决啥","db-common","技术说明里出现“{}”，非东北读者是否能立刻理解且不出戏？"),
...items("老铁|嘎嘎|咱就是说|你寻思|嘎哈|咋地|老鼻子|贼拉|嗷嗷|杠杠的|麻溜儿|得瑟|埋汰|磕碜|膈应|刺挠|秃噜|整岔劈了|虎了吧唧|二虎吧唧|五迷三道|吭哧瘪肚|磨叽|闹挺|稀罕|敞亮|尿性|掉链子|扯犊子|犊子|瘪犊子|山炮|傻狍子|波棱盖|哈喇子|嘎达|旮旯|苞米|马葫芦|扑棱|嘚瑟|嘚啵|忽悠|唠嗑|唠明白|唠两句|老带劲了|可劲儿|一个劲儿|备不住|兴许|保不齐|指定|妥妥的|必须的|那可不|可拉倒吧|别扯了|咋咋呼呼|急头白脸|鼻子不是鼻子脸不是脸","db-marked","“{}”也许有地域或表演色彩。技术解释里应该放在哪条边界？")];
const termGroups={
"general-tech":"LLM|agent|code|repo|bug|Git|GitHub|CPU|GPU|RAM|VRAM|model|dataset|API|CLI|SDK|IDE|OS|Linux|macOS|Windows|server|client|database|network|cloud|Docker|container|JSON|YAML|HTTP|URL|UI|frontend|backend|open source|commit|branch|token|prompt|context|benchmark|latency|throughput|memory|cache|thread|process|log|debug|build|deploy|test|production",
"software":"worktree|rebase|merge commit|fast-forward|HEAD|index|staging area|detached HEAD|event loop|callback|promise|future|coroutine|async/await|race condition|deadlock|mutex|semaphore|atomic operation|memory ordering|garbage collection|heap|stack|virtual memory|system call|scheduler|dependency injection|dependency inversion|inversion of control|interface|abstraction|encapsulation|polymorphism|middleware|RPC|REST|GraphQL|webhook|idempotency|transaction|ACID|isolation level|eventual consistency|cache invalidation|TTL|write-through cache|message queue|pub/sub|backpressure|load balancing|sharding|replication|consensus|leader election|CAP theorem|container image|namespace|cgroup|overlay filesystem|orchestration|Kubernetes|CI/CD",
"ml-systems":"gradient|optimizer|optimizer step|batch|microbatch|epoch|learning rate|loss|evaluation metric|backpropagation|autograd|gradient accumulation|gradient checkpointing|mixed precision|quantization|calibration|zero-point|tensor|embedding|attention|self-attention|KV cache|prefill|decode|context window|inference|training|fine-tuning|pretraining|LoRA|adapter|checkpoint|activation|parameter|weight decay|regularization|overfitting|underfitting|dropout|batch normalization|layer normalization|distributed data parallelism|DDP|data parallelism|model parallelism|tensor parallelism|pipeline parallelism|all-reduce|NCCL|CUDA|kernel|GPU utilization|memory bandwidth|compute-bound|memory-bound|OOM|FLOPS|TFLOPS|latency percentile",
"stats-math":"mean|median|variance|standard deviation|correlation|causation|probability distribution|likelihood|prior|posterior|Bayes theorem|null hypothesis|alternative hypothesis|p-value|confidence interval|credible interval|statistical significance|effect size|power|Type I error|Type II error|sampling bias|confounder|randomization|regression|linear regression|logistic regression|Poisson regression|link function|offset|exposure|overdispersion|residual|coefficient|intercept|regularization|L1|L2|cross-validation|bootstrap|maximum likelihood|gradient descent|convexity|eigenvalue|matrix rank|Jacobian|Hessian|normalization"};
const terminologyCandidates=Object.entries(termGroups).flatMap(([category,raw])=>items(raw,`term-${category}`,"对跨领域技术读者，英文术语 `{}` 第一次有意义地出现时该怎么处理？"));
window.annotationData={version:DB_VERSION,dongbei:dongbeiCandidates,terms:terminologyCandidates};
